version: '3.8'

services:
  pytorch-agent:
    image: pytorch-agent:latest
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - gpus=all
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    command: python ./main.py
